version: "3"

services:
  app:
    build: "./config/nginx"
    container_name: bp_nginx
    volumes:
      - "./app:/var/www/html"
      - "./config/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "80:80"
    links:
      - php
  php:
    build: "./config/php-fpm"
    container_name: bp_php
    volumes:
      - "./app:/var/www/html"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      XDEBUG_CONFIG: remote_host=docker.for.mac.localhost remote_port=9001
  composer:
    image: composer
    volumes:
      - "./app:/app"
  mysql:
    image: mysql
    container_name: bp_mysql
    restart: always
    env_file:
        - ".env"
    environment:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
        - "3306:3306"
    volumes:
        - "./data/db/mysql:/var/lib/mysql"