version: '3'

services:
  app:
    build: './config/nginx'
    volumes:
      - './app:/usr/share/nginx/html'
    ports:
      - '80:80'
  php:
    build: './config/php-fpm'
    volumes:
      - './apps:/usr/share/nginx/html'
    ports:
      - '9000:9000'