version: "3"

services:
  app:
    build: "./config/nginx"
    volumes:
      - "./app:/var/www/html"
      - "./config/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "80:80"
    links:
      - php
  php:
    build: "./config/php-fpm"
    volumes:
      - "./app:/var/www/html"
    ports:
      - "9000:9000"